language: node_js

node_js:
  - "stable"

# notifications:
#   email: false

# before_deploy:
#   - npm run build
#   - echo -e "node_modules\npackage-lock.json" > .gitignore

script:
  - npm run build

after_success:
- echo 'node_modules' > .gitignore
- echo $CNAME > CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master
